# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

variables:
  bicepFile: 'Infra/site.bicep'
  azureServiceConnection: 'azure'
  groupName: 'rg-biceptest'
  location: 'uksouth'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: batch
    scriptLocation: inlineScript
    inlineScript: |
      call az --version
      call az group create --name $(groupName) --location $(location) 
      call az deployment group create --resource-group $(groupName) --template-file $(bicepFile)
      